
["Turret stats"]

	["Turret stats"."Fire charge turret"]
		#In ticks
		#Range: 1 ~ 60
		"Fire rate" = 20
		#Range: 10.0 ~ 1.7976931348623157E308
		Health = 60.0
		#Range: 0.0 ~ 100.0
		Armor = 3.0
		#Range: 8.0 ~ 128.0
		Range = 32.0
		#Range: 1 ~ 100
		Damage = 6

	["Turret stats"."Storage drone"]
		#Range: 10.0 ~ 1.7976931348623157E308
		Health = 60.0
		#Range: 0.0 ~ 100.0
		Armor = 0.0

	["Turret stats"."Brick turret"]
		#Range: 1 ~ 100
		"Brick damage" = 9
		#In ticks
		#Range: 1 ~ 60
		"Fire rate" = 20
		#Range: 10.0 ~ 1.7976931348623157E308
		Health = 60.0
		#Range: 0.0 ~ 100.0
		Armor = 3.0
		#Range: 8.0 ~ 128.0
		Range = 32.0

	["Turret stats"."Gauss turret"]
		#In ticks
		#Range: 1 ~ 60
		"Fire rate" = 20
		#Range: 10.0 ~ 1.7976931348623157E308
		Health = 60.0
		#Range: 0.0 ~ 100.0
		Armor = 3.0
		#Range: 8.0 ~ 128.0
		Range = 32.0
		#Range: 1 ~ 100
		Damage = 12

	["Turret stats"."Arrow turret"]
		#In ticks
		#Range: 1 ~ 60
		"Fire rate" = 20
		#Range: 10.0 ~ 1.7976931348623157E308
		Health = 60.0
		#Range: 0.0 ~ 100.0
		Armor = 3.0
		#Range: 1 ~ 100
		"Base damage" = 6
		#Range: 8.0 ~ 128.0
		Range = 32.0

	["Turret stats"."Bullet turret"]
		#In ticks
		#Range: 1 ~ 60
		"Fire rate" = 20
		#Range: 10.0 ~ 1.7976931348623157E308
		Health = 60.0
		#Range: 0.0 ~ 100.0
		Armor = 3.0
		#Range: 1 ~ 100
		"Iron bullet damage" = 8
		#Range: 8.0 ~ 128.0
		Range = 32.0

	["Turret stats"."Cobble turret"]
		#In ticks
		#Range: 1 ~ 60
		"Fire rate" = 20
		#Range: 10.0 ~ 1.7976931348623157E308
		Health = 60.0
		#Range: 0.0 ~ 100.0
		Armor = 3.0
		#Range: 0.0 ~ 128.0
		Range = 32.0
		#Range: 1 ~ 100
		Damage = 3

[Common]
	"Set ownership automatically" = true
	#Range: 1 ~ 128
	"Drones will keep to the owner at such distance" = 30
	#Range: 0.1 ~ 50.0
	"Turret and drone projectile speed" = 50.0
	#List of mob ids to be excluded from default targets
	"Target list exceptions" = ["minecraft:zombified_piglin"]

